config/routes.rb
Rails.application.routes.draw do

  resources :todos

  root 'todos#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	def index
		@todos = Todo.all
	end

	def new
		@todo = Todo.new
	end

	def create
		@todo = Todo.new(todo_params)
		if @todo.save
			flash[:success] = "Todo was successfully created."
			redirect_to root_url
		else
			flash[:alert] = 'There was a problem creating the Todo.'
			render :new
		end
	end	

	def show
		@todo = Todo.find(params[:id])
	end

	def edit
		@todo = Todo.find(params[:id])
	end

	def update
		@todo = Todo.find(params[:id])
		if @todo.update_attributes(todo_params)
			flash[:success] = "Todo was successfully updated."
			redirect_to root_url
		else
			flash[:alert] = 'There was a problem updating the Todo.'
        	render :edit
		end
	end

	def destroy
		@todo = Todo.find(params[:id]).delete
		flash[:success] = "Todo was successfully deleted."
		redirect_to root_url
	end

	private
		def todo_params
			params.require(:todo).permit(:title, :notes)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<title><%= content_for?(:title) ? yield(:title) : "Todo App" %></title>

	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'shared/navigation' %>

	<div class="row">
	  <% flash.each do |name, msg| %>
	    <% if msg.is_a?(String) %>
	      <%= content_tag :div, msg, class: "alert-box #{name} radius" %>
	    <% end %>
	  <% end %>
	</div>

	<div class="l-container">
		<main class="l-container__main">
			<%= yield %>
		</main>
		<aside class="l-container__sidebar">
			<h3>Sidebar Placeholder</h3>
		</aside>
	</div>
	
	<%= javascript_include_tag "application" %>
</body>
</html>

app/views/shared/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">Todo Navigation</a></h1>
    </li>

    <li class="toggle-topbar">
      <a href="#"><span>Menu</span></a>
    </li>
  </ul>

<section class="top-bar-section">
  <ul class="right">
    <li class="has-dropdown no-click">
      <a href="#">Menu</a>
      <ul class="dropdown">
        <li><a href="#">Login</a></li>
        <li><%= link_to "Create a todo", new_todo_path %></li>
      </ul>
    </li>
  </ul>
</section>

</nav>

app/views/todos/edit.html.erb
<h1>Create a new to-do item</h1>

<%= form_for @todo, url: todo_path, method: :patch do |f| %>
	<%= f.text_field :title %>
	<%= f.text_field :notes, size: "60x12" %>
	<%= f.submit "Update" %>
<% end %>

app/views/todos/index.html.erb
<h1>Your to-do list:</h1>
<dl class="tabs" data-tab data-options="deep_linking: true">
  <dd class="active">
    <%= link_to 'View list', todos_path %>
  </dd>
  <dd>
    <%= link_to 'New todo', new_todo_path %>
  </dd>
</dl>
<table>
	<thead>
		<tr>
			<th>Title</th>
			<th>Notes</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
		<% @todos.each do |todo| %>
			<tr>
				<td>
				  <span data-tooltip aria-haspopup="true" class="has-tip tip-left" title="<%= "Created on #{todo.created_at.strftime("%m%e%Y at %w:%M %p")}, Last modified on #{todo.updated_at.strftime("%m%e%Y at %w:%M %p")}" %>">
				    <%= todo.title %>
				  </span>
				</td>
				<td>
					<% if todo.notes? %>
						<a data-open="todo-<%= todo.id %>-notes">View notes</a>

						<div class="reveal" id="todo-<%= todo.id %>-notes" data-reveal>
							<%= todo.notes %>
							<div>
								<button class="close-button" data-close aria-label="Close modal" type="button">
								    <span aria-hidden="true">Close</span>
								</button>
						   </div>
						</div>
					<% end %>
				</td>
				<td><%= link_to 'Show', todo, class: "button-alter" %></td>
				<td><%= link_to 'Edit', edit_todo_path(todo), class: "button-alter" %></td>
				<td><%= link_to 'Delete', todo, method: :delete, data: { confirm: 'Are you sure?' }, class: "button-alter" %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<%= link_to "New to-do item", new_todo_path, class: "button-new" %>

app/views/todos/new.html.erb
<h1>Create a new to-do item</h1>
<dl class="tabs" data-tab data-options="deep_linking:true">
  <dd>
    <%= link_to 'View list', todos_path %>
  </dd>
  <dd class="active">
    <%= link_to 'New todo', new_todo_path %>
  </dd>
</dl>

<h1>New todo</h1>
<%= link_to 'Back', todos_path %>

<% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

<%= form_for @todo, url: { action: "create" } do |f| %>
	<div class=".l-container">
		<div class="small-10">
			<div class=".l-container">
				<div class="small-2 columns">
					<%= f.label :title, class: "right inline" %>
				</div>
				<div class="small-10 columns">
					<%= f.text_field :title %>
				</div>
			</div>
		</div>

		<div class="small-10">
			<div class=".l-container">
				<div class="small-2 columns">
					<%= f.label :notes, class: "right inline" %>
				</div>
				<div class="small-10 columns">
					<%= f.text_field :notes, size: "60x12" %>
				</div>
			</div>
		</div>

		<div class="small-10">
			<div class=".l-container">
				<div class="small-10 small-offset-2 columns">
					<%= f.submit "Create" %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/todos/show.html.erb
<h1><%= @todo.title %></h1>
<p><%= @todo.notes %></p>
<%= link_to 'Back', root_path %>
<%= link_to 'Edit', edit_todo_path(@todo) %>
<%= link_to 'Delete', @todo, method: :delete, data: { confirm: 'Are you sure?' } %> 